version: '1.0'
services:
  back_app:
    build: .
    volumes:
      - myinitdb:/bimend-test/libs/
    ports:
      - "3500:3500"
    environment:
      - SERVER_PORT=3500
      - DB_USER=bimend
      - DB_HOST=db
      - DB_NAME=bimend
      - DB_PASS=admin
  db:
    image: "postgres"
    volumes:
      - myinitdb:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=bimend
      - POSTGRES_DB=bimend
  front_app:
    image: "geos74/test-task-front"
    ports:
      - "3000:3000"
    environment:
      - SERVER_PORT=3000
      - BACKEND_HOST=localhost
      - BACKEND_PORT=3500
volumes:
  myinitdb: